In [145]:
import pandas as pd
import requests
import datetime as dt

tickers = ['AAPL','AMZN', 'TSLA', 'GE', 'MSFT']

end = dt.date.today()
start = end - dt.timedelta(days=365*2)

def portfolio_creator(tickers, start, end):
    '''
    Gets tickers from tiingo and creates a portfolio dataframe
    '''
    
    headers = {
            'Content-Type': 'application/json',
            'Authorization': #enter tiingo api key here
            }
        
    for ticker in tickers:
        requestResponse = requests.get('https://api.tiingo.com/tiingo/daily/'
                                   + ticker +'/prices?startDate='+str(start)+'&endDate='+str(end),
                                        headers=headers)
        
        df = pd.DataFrame(requestResponse.json())
        df = df.loc[:,['date', 'adjClose']]
        df = df.rename(columns={'adjClose':ticker})  
        df.set_index('date',inplace=True)
        
        if ticker == tickers[0]:
            portfolio_df = df
        else:
            portfolio_df = pd.merge(portfolio_df,df, how='left', left_index=True, right_index=True)

    return portfolio_df

portfolio_df = portfolio_creator(tickers, start, end)
portfolio_df.to_csv('portfolio hist')

In [154]:
portfolio_df = portfolio_creator(tickers, start, end)

In [157]:
portfolio_df.to_csv('portfolio hist')

In [158]:
portfolio_df

                                AAPL     AMZN     TSLA         GE        MSFT
date
2018-12-18T00:00:00.000Z   40.550288  1551.48   67.406   6.937528  101.372654
2018-12-19T00:00:00.000Z   39.285457  1495.08   66.594   7.309181  101.099649
2018-12-20T00:00:00.000Z   38.294103  1460.83   63.076   7.099257   98.974109
2018-12-21T00:00:00.000Z   36.804630  1377.45   63.954   6.822538   95.776049
2018-12-24T00:00:00.000Z   35.852344  1343.96   59.078   6.603072   91.778474
...                              ...      ...      ...        ...         ...
2020-12-11T00:00:00.000Z  122.410000  3116.42  609.990  11.160000  213.260000
2020-12-14T00:00:00.000Z  121.780000  3156.97  639.830  10.830000  214.200000
2020-12-15T00:00:00.000Z  127.880000  3165.12  633.250  11.110000  214.130000
2020-12-16T00:00:00.000Z  127.810000  3240.96  622.770  10.930000  219.280000
2020-12-17T00:00:00.000Z  128.700000  3236.08  655.900  10.880000  219.420000

[505 rows x 5 columns]